AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring API - my.service::my-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.demo.spring.mvc.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-mvc-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greeting/Bill'
    Export:
      Name: MyServiceApi
